### ISSUE TITLE
Решить, как будем хранить граф

### ISSUE THREAD

**Issue by GeorgiySurkov** [webebers/city-view#12]

**Comment by GeorgiySurkov** [comment]
Пайплайн получения данных выглядит примерно так:

1. Данные достаются из открытого источника OSM через overpass API.
   1. Максимальная возможная предобработка в Overpass QL
2. Данные из OSM формата переводятся в GeoJSON (мб этот этап можно пропустить). Я делал через npm пакет osmtogeojson. Надо будет найти подходящий питон пакет для этого.
3. Перевод данных в GeoPackage для быстрого рендеринга и хранения в одном файле.

**Comment by GeorgiySurkov** [comment]
Таким образом храним граф в Geopackage

**Comment by GeorgiySurkov** [comment]
Возможно стоит взять все-таки spatialite. пишут, что она лучше подходит для локального хранилища в проекте, а geopackage больше подходит для транспорта данных (хотя на саммо деле обертка над spatialite). В spatialite мы сможем использовать всю мощь обычной sql базы данных.

**Comment by AnatolyShev** [comment]
Я немного посмотрел на specialite, и, думаю, нам действительно можно её использовать.

**Comment by nermakovaa** [comment]
@GeorgiySurkov у тебя есть какие-нибудь идеи по хранению графа и его отображению в QGIS? Может до четверга попробуем взять алгоритмы из QGIS по графу и интегрировать их в нашу среду? (как минимум выделить и отобразить граф)

**Comment by GeorgiySurkov** [comment]
Инструменты для вычисления метрик дорожной сети города, которые я успел попробовать в QGis, получают на вход слой и отдают слой с выходными метриками. Этот алгоритм строит в процессе работы граф, но не выводит его.

Возможно заказчику и не нужно выводить конкретно граф, а достаточно будет получить только метрики.

**Comment by GeorgiySurkov** [comment]
Раз мы стали работать с osmnx (networkx), то логичнее всего сохранять граф в их формате

https://osmnx.readthedocs.io/en/stable/user-reference.html#osmnx.io.save_graph_geopackage
