### ISSUE TITLE
Добавить правки в ТЗ

### ISSUE THREAD

**Issue by nermakovaa** [webebers/city-view#19]
Доработать архитектуру приложения - как будем хранить граф, как будем к нему обращаться. Версия с плагинами остается, веб-версию убираем. 

Доработать ТЗ и отправить заказчику.  

https://docs.google.com/document/d/1snAvnH-A0FP1Cz45PaOXdyENaN67yit3ljeTxY8rBdI/edit#heading=h.5r670k9y30yn

**Comment by sevryukov** [comment]
@AnatolyShev с момента возникновения задачи по правке ТЗ (после встречи с заказчиком #14) прошло почти три недели, включая неделю интенсива и длинные выходные. Что стало проблемой в правке ТЗ?

**Comment by GeorgiySurkov** [comment]
@AnatolyShev @nermakovaa 
Друзья, как у нас обстоит дело с обновлением ТЗ в связи с правками. Мы на первое время завели задачи и начали делать их, но только потому что времени мало и слишком дорого блокироваться всей командой, пока не появится четкое ТЗ. Чем больше мы ставим задача вслепую без ТЗ, тем больнее потом будет натягивать сделанную нами работу под реальные требования заказчика. Для декомпозиции и планирования следующих задач нам нужно ТЗ. 

Обращайтесь за помощью, если чувствуете, что что-то не получается.

**Comment by nermakovaa** [comment]
@GeorgiySurkov займись, пожалуйста, составлением нового ТЗ в соответствие с правками, думаю это твоя задача как техлидера, поскольку нам необходимо внутреннюю составляющую проекта расписать (как у нас плагин будет устроен и какие библиотеки мы будем использовать)

**Comment by nermakovaa** [comment]
В ближайшее время буду редактировать [Новое ТЗ](https://docs.google.com/document/d/1UvPPDeT9PFe8KrQOCWG7boKwvitKcU4u9L7rLm_dN50/edit?usp=sharing)
ссылку на него прикрепила, доступ для редактирования всем открыла

**Comment by nermakovaa** [comment]
Опиралась на то что мы имеем на данный момент [Новое ТЗ](https://docs.google.com/document/d/1UvPPDeT9PFe8KrQOCWG7boKwvitKcU4u9L7rLm_dN50/edit?usp=sharing)
@GeorgiySurkov @AnatolyShev 
@GeorgiySurkov можешь добавить информацию, связанную с хранением графа, либо что-то иное - что посчитаешь нужным в разрабатываемой системе

**Comment by GeorgiySurkov** [comment]
https://github.com/webebers/city-view/issues/34
