### ISSUE TITLE
Исследовать, как в QGIs выводить информацию по точкам на карте

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#27]
Исследовать возможные инструменты: выделение цветом/ вывод текстовой информации/ вывод числовых значений. 
В соответствие с ТЗ решить, какие инструменты нам понадобятся.

**Comment by sevryukov** [comment]
@AnatolyShev речь ведь идёт о выводе точки в QGIS?
Кстати, я бы рекомендовал задачу по составлению подборки информационных ресурсах о QGIS (будет небольшая база знаний, которой смогут воспользоваться все участники проекта).

**Comment by AnatolyShev** [comment]
@sevryukov Как пояснил Гоша, нужно исследовать, как выводить информацию о точках нашего графа на карте, т.е. их характеристики, например, связность или коэффициент кластеризации и т.д.

**Comment by sevryukov** [comment]
@AnatolyShev @GeorgiySurkov если мы говорим о выводе точек в QGIS (вы так и не подтвердили), то тут всё достаточно однозначно и относительно просто. Была бы подборка ресурсов о QGIS, мог бы сослаться (почему и предложил сделать подборку). Но в общем и без неё сошлюсь на первое найденное видео: https://www.youtube.com/watch?v=-B96bCts_Eg

В пространстве можно вывести полигон, описывающий точки графа, можно вывести центроид, можно к полигону добавить характеристики графа, но не более.

В общем надо более чётко описать задачу и ожидаемый результат, иначе откуда из исходной формулировки можно понять, что, к примеру, надо выводить коэффициент кластеризации.
И вновь обращу внимание - граф != пространственные данные, в QGIS не вывести граф (можно вывести его репрезентацию).

**Comment by GeorgiySurkov** [comment]
В нашем итоговом продукте граф будет некоторым образом визуализирован на карте. Вершины в нем будут представлены точками. По ТЗ нам надо будет считать некоторые величины для вершин графа. Эти величины нам необходимо визуализировать, отображать. В задаче как раз нужно исследовать, как можно донести пользователю информацию о характеристиках вершины в топологии исселдуемого города. Например, вершине графа, отображаемой как круг, точно можно задать цвет или радиус. Возможно, в QGis можно сделать вывод какого-то pop-up по нажатию на вершину, в котором можно еще какую-то информацию вывести по вершине. В принципе, если будут хотя бы эти способы визуализации данных, то мы точно не пропадем и сможем выводить вычисленные нами характеристики вершин.

**Comment by sevryukov** [comment]
@AnatolyShev Слой состоит из фич, фичи описываются с помощью атрибутов, значения атрибутов используются для визуализации. Фичи и их атрибуты формируются и сохраняются в файлах подходящего формата (в зависимости от типа слоя и фич). Если и задаваться вопросом "как сформировать набор фич с заданным набором атрибутов программно", то следует искать решение в области работы с данными и их сохранения в формате, который позволяет это сделать и поддерживается QGIS.
Возьмите, к примеру, [GeoJSON](https://ru.wikipedia.org/wiki/GeoJSON) и используйте его (до тех пор, пока не поймёте, что есть требования, которым этот формат не удовлетворяет).

@GeorgiySurkov предлагаю этот комментарий рассматривать среди прочего и как комментарий к #25

**Comment by GeorgiySurkov** [comment]
@sevryukov я сам изначально склонялся к использованию geojson, но он как раз стал не удовлетворять по скорости рендеринга (Подробнее описал в https://github.com/webebers/city-view/issues/25#issuecomment-1828610329). С использование spatialite проблема скорости рендеринга исчезла.

**Comment by sevryukov** [comment]
@GeorgiySurkov понял. Но в таком случае в ТЗ скорее должно быть требование к производительности, а не к формату.
А ещё ценны размышления, которые Вы привели, но не в ответ на вопрос, а как аргументация к той или иной задаче или в виде комментария по ходу решения.
