### ISSUE TITLE
Исследовать работу со стилями QGIS

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#28]
Исследовать возможные инструменты: выделение цветом/ вывод текстовой информации/ вывод числовых значений.
В соответствие с ТЗ решить, какие инструменты нам понадобятся.

**Comment by sevryukov** [comment]
@AnatolyShev @nermakovaa границы районов обычно выводятся в виде набора полигонов.
Согласен с тем, что надо изучить работу со стилями и геометрическими примитивами в QGIS, но кажется в этом случае не обязательно привязывать задачу к районам.

**Comment by nermakovaa** [comment]
Решила, что с этой задачей будем разбираться когда у нас появится карта города. Пока остановилась на пользовательском интерфейсе, так или иначе нам его реализовывать предстоит. Пока пытаюсь с помощью Qt Designer создать простой плагин из серии: 


![Image](https://github.com/webebers/city-view-back/assets/114575973/245cd1bd-6b16-406c-9af0-bb9c0ad5fafc)

только в нашем случае это будет выбор города из предложенного перечня, эти два модуля (ниже) позволят нам это реализовать


![Image](https://github.com/webebers/city-view-back/assets/114575973/5e7b9f2e-f814-4626-bdff-35f418720842)


Как только появится хоть что-то готовое, - залью в репозиторий, в перспективе можем с эти работать, + добавить наработки Футао с выбором слоя и т.д.
@AnatolyShev @GeorgiySurkov @WenFutao

**Comment by nermakovaa** [comment]
Добавила тестовый плагин (пока что без всего) https://github.com/webebers/city-view-back.git
