### ISSUE TITLE
Сделать тестовый плагин, который будут регистрироваться в QGis

### ISSUE THREAD

**Issue by GeorgiySurkov** [webebers/city-view#29]
Плагин ничего не должен делать. Главное, чтобы его можно было добавить в QGis без ошибок. Затем в этот плагин мы уже будем добавлять фичи нашего продукта.

**Comment by nermakovaa** [comment]
Создан тестовый плагин https://github.com/webebers/city-view-back.git, инструкция по тому как его запустить содержится в репозитории
@GeorgiySurkov
