### ISSUE TITLE
Запрограммировать упаковку geojson файлов в geopackage в среде QGis

### ISSUE THREAD

**Issue by GeorgiySurkov** [webebers/city-view#33]
Внутри нашего приложения мы будем работать с простым форматом geojson. Но он слишком медленно отрисовывается, поэтому нам нужно преобразовывать его в формат, который поддерживает пространственное индексирование. Например, для этого подходит geopackage.

В результате задачи должен быть сделан скрипт, который упаковывает geojson файл в geopackage с помощью QGIS api.

**Comment by nermakovaa** [comment]
@GeorgiySurkov я также видела что многие переводят geojson в shp формат для отрисовки - поскольку с ним в qgis все молниеносно обрабатывается, ты geopackage с ним не сравнивал?

**Comment by GeorgiySurkov** [comment]
@nermakovaa 
shp это shapefile, как я понял? 

Нет, я его не пробовал, потому что sqlite и geopackage были достаточно быстрыми, и я решил остановиться на них. В этой задаче можно попробовать и shapefile тоже. Если он будет действительно еще быстрее или удобнее для работы с ним, то можно использовать его.

**Comment by GeorgiySurkov** [comment]
По итогу получилось сделать слой, который хранит фичи в оперативной памяти в формате, который использует qgis у себя в памяти.
