### ISSUE TITLE
Созвониться с заказчиком

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#39]
@AnatolyShev @GeorgiySurkov @WenFutao всем привет, предлагаю написать заказчику и договориться с ним о встрече завтра (во вторник), чтобы представить результаты которые есть на данный момент и обсудить план последующего анализа

**Comment by AnatolyShev** [comment]
Поддержу предложение. Если все будут согласны - напишу Александру Юрьевичу.

**Comment by GeorgiySurkov** [comment]
Поддерживаю. Давайте составим план встречи.

Пункты в повестку:
- Показать новое ТЗ
- Обсудить, как мы сможем максимально помочь своим продуктом заказчику, с учетом оставшегося времени и новой концепции проекта в виде плагина qgis.

Что еще?

**Comment by nermakovaa** [comment]
Думаю про отчет спрашивать не нужно, это же обязательное условие практики, тем более у нас пока более важные задачи есть. Поскольку заказчик хотел работать с графом, считаю, что нам следует подумать как его добавить и обращаться к нему (желательно до четверга), чтобы этот момент обсудить и подумать какой анализ по графу можно сделать. 

@GeorgiySurkov @AnatolyShev

**Comment by nermakovaa** [comment]
- узнать, нужно ли хранить/выводить конкретный граф или достаточно получить только метрики

**Comment by nermakovaa** [comment]
Что было на встрече. Кратко.

Нужно реализовать граф для решения задачи кластеризации объектов недвижимости. Необходимо включить объекты недвижимости в графовую структуру. Надо понять из каких имеющихся компонент это можно сделать. Задача - чтобы для любого города мы могли получать граф – например в виде слоя или хотя бы какой-то структуры данных. 
Где:
- узел - какой-то объект недвижимости (любой объект недвижимости описывается множеством точек - нам достаточно получить одну единственную точку - центр масс этих точек)
- дуги должны соединять эти объекты
@GeorgiySurkov @AnatolyShev @WenFutao

**Comment by AnatolyShev** [comment]
Результаты встречи;
- визуализацию графа УДС города выводить нужно (в этом, собственно, заключалась основная задача при реализации проекта)
- в граф УДС нужно включить объекты недвижимости
- следующая встреча с Александром Юрьевичем первично назначена 14.12.2023.
