### ISSUE TITLE
Дозаполнить шаблон презентации для экспертов уч.практики

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#41]
Необходимо дозаполнить шаблон презентации, выданный нам для презентации проекта экспертам учебной практики. Конкретные слайды: Traction, Unit-economics, Запрос, Планы на 3 года, Рынок.

**Comment by AnatolyShev** [comment]
В одном из пунктов презентации требуется считать Unit-экономику. Вот материалы, высланные бизнес трекером для этого:

[Юнит Экономика-4.xlsx](https://github.com/webebers/city-view/files/13549213/-4.xlsx)

[юнит_экономика_ueCalc_–_поиск_целевых_метрик_в_юнит_экономике_испр.xlsx](https://github.com/webebers/city-view/files/13549214/_._ueCalc_._._._._._._._.xlsx)

[2_5436289232106700223.xlsx](https://github.com/webebers/city-view/files/13549216/2_5436289232106700223.xlsx)

**Comment by nermakovaa** [comment]
@AnatolyShev тебе не кажется что это все можно по конкретным задачам раскидать с детальным описанием того что нужно сделать? И назначить дедлайны (кажется они на этом задании есть). Я пока не понимаю какие слайды требуется заполнить и в какие из них нужно Unit-экономику интегрировать. Мне кажется ее расчет - это отдельная задача, как и рынок

**Comment by AnatolyShev** [comment]
Дозаполнил шаблон. Проверяйте.
