### ISSUE TITLE
Посчитать unit-экономику по проекту

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#42]
Необходимо посчитать unit-экономику для дозаполнения шаблона презентации проекта (issue #41)

**Comment by AnatolyShev** [comment]
Дополнительные материалы, выданные нашим бизнес трекером, для ознакомления и выполнения задачи:

[2_5436289232106700223.xlsx](https://github.com/webebers/city-view/files/13561247/2_5436289232106700223.xlsx)

[Юнит Экономика-4.xlsx](https://github.com/webebers/city-view/files/13561250/-4.xlsx)

[юнит_экономика_ueCalc_–_поиск_целевых_метрик_в_юнит_экономике_испр.xlsx](https://github.com/webebers/city-view/files/13561257/_._ueCalc_._._._._._._._.xlsx)

**Comment by nermakovaa** [comment]
Посчитала, но тут скорее общая оценка ожидаемой от проекта прибыли https://docs.google.com/spreadsheets/d/1CY8T8Hu4Eam_1w4Vsqg9gGXmqHAGBcItzS4Vj09__M8/edit?usp=sharing
