### ISSUE TITLE
Составить Отчёт по учебной практике

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#43]
Необходимо составить Отчёт по учебной практике, шаблон которого был выслан Иваном Станиславовичем в Тимс:
https://studentspburu.sharepoint.com/:w:/s/2023IT-/EY5uRvtTO8FKsuLTsu_VnqUBJs6EQT5OjDIgUgb2-7UeTg?e=sSKvR4.

https://docs.google.com/document/d/1mngJKX50WsGxiw2pDlpoR_3AHvwD6rk8/edit

**Comment by dipmoaiaismo** [comment]
Заполнил первые три пунка по отчету практики. При необходимости прошу внести корректировки. Для заполнения следующих пунктов необходимы технические знания, так как , там нужно описать какие технические решения мы применяли и почему именно их мы выбрали. Прошу вас помочь с заполнением следующих пунктов. Спасибо!

**Comment by AnatolyShev** [comment]
@dipmoaiaismo Да, я проверил все пункты и подкорректирую их. А так, в целом, написано хорошо, Фаррух.

**Comment by AnatolyShev** [comment]
@nermakovaa @dipmoaiaismo @GeorgiySurkov @WenFutao Доделал главы "Выводы", "Анализ хода проекта". Проверяйте, ребята.

**Comment by AnatolyShev** [comment]
По результатам сегодняшнего интервьюирования, необходимо внести изменения в Отчёт по учебной практике, а именно отредактировать роли некоторых участников команды: мои и Надины.
