### ISSUE TITLE
Добавить выбор нескольких типов дорог и зданий в выборе добавления слоя

### ISSUE THREAD

**Issue by GeorgiySurkov** [webebers/city-view#45]
Сейчас в пользовательскои интерфейсе можно выбрать только один тип дороги. Нужно добавить поддержку выбора нескольких.

![Image](https://github.com/webebers/city-view/assets/35404780/6800f3c6-8976-4bdf-8f96-4e3fefc67a9b)

**Comment by nermakovaa** [comment]
Добавила поддержку выбора нескольких типов дорог и зданий. Теперь это так выглядит.

![Image](https://github.com/webebers/city-view/assets/114575973/be9f69d0-e546-4fc5-8846-7eb6f47db36a)
