### ISSUE TITLE
Реализовать построение топологии города с помощью OSMnx

### ISSUE THREAD

**Issue by nermakovaa** [webebers/city-view#48]
Добавила ноутбук с координатами зданий (центры масс) и графом дорог (с перекрестками - там еще узлы это не только перекрестки но и тупики дорог - может их следует убрать), лежат по этому пути https://github.com/webebers/city-view/blob/master/notebook/notebook.ipynb

Думаю нужно объединить усилия и решить следующие задачи
- объединить эти два "графа" (помним что искомый граф - это кратчайшее расстояние от центров зданий до графа дорог - до самих дорог - дуг - линий)
- подумать как мы можем хранить граф, чтобы отобразить его в qgis (может и не нужно хранить, главное решить задачу с отображением) - посмотрела, вроде бы довольно просто в QGIS отображается
- добавить то что получится в плагин

Можете подумать/взять эти задачи @GeorgiySurkov @AnatolyShev @WenFutao, есть ли какие-нибудь предложения как это можно реализовать

**Comment by nermakovaa** [comment]
Пока мне удалось сделать нечто такое, как вы думаете, это может быть тем, что хотел от нас заказчик? @GeorgiySurkov @AnatolyShev @WenFutao  
Тут я просто добавила полученные на предыдущем этапе слои в QGIS и использовала встроенный алгоритм кратчайших линий между объектами, если все соединить, то будто бы получается искомый граф. Я не нашла способ как это все с помощью OSMnx провернуть, но может быть он и есть. Может быть стоит еще от тупиков избавиться


![Image](https://github.com/webebers/city-view/assets/114575973/0235a579-3fa6-4616-b841-25653bd0788d)

**Comment by GeorgiySurkov** [comment]
> как вы думаете, это может быть тем, что хотел от нас заказчик?

@nermakovaa Так давайте у заказчика напрямую спросим? С ним ведь можно на связь выйти.

**Comment by nermakovaa** [comment]
Нет, пока это не граф, а набор отдельных слоев, заказчик же хотел получить граф, насколько я помню.
Кроме того это лишь часть, в ноутбуке указала (только Васильевский остров), полностью такие слои для всего города подгрузить не получается, все слетает через какое-то время обработки, пыталась данные в файл записывать, но тут аналогичная ситуация.
Подумала, что через запрос api можно такие же данные получить, именно центры зданий - правда там они не такие полные ([out:json];area["name"="{city_name}"]->.a;node(area.a)["building"];way(area.a)["building"];relation(area.a)["building"];out center;), как если это делать через встроенную в osmnx опцию. Однако в таком случае для перекрестков проблемы возникают, ибо они там обозначены как просто перекрестки без пересечения улиц (грубо говоря где люди дорогу переходят).
Также не уверена насчет кратчайшего расстояния, мне кажется как часть графа эти линии добавить не получится, поскольку они накладываются на дорогу, но не соединяются с ней в узле.
Что касается объединения слоев, то я пыталась это через встроенный метод в osmnx сделать, но не получилось (который находит кратчайшее расстояние к ребрам nearest_edges), кроме того пыталась использовать GRASS в qgis но там свои проблемы возникают.
Нужна ваша помощь @GeorgiySurkov @WenFutao @AnatolyShev

**Comment by nermakovaa** [comment]
Нашла такую статью https://habr.com/ru/articles/511144/ кажется первая часть похожа на то что мы хотим с графом сделать, там вроде бы PgRouting 3.0 и PostgreSQL 12 используют, попытаюсь повторить. https://docs.pgrouting.org/3.0/en/index.html с помощью этого можно кратчайшие расстояния найти. https://github.com/amauryval/OsmRx такое еще находила, у них в ноутбуке пример есть, пыталась его для спб запустить (разные запросы использовала по типу Санкт-Петербург, Санкт Петербург, Saint Petersburg, Saint-Petersburg, St. Petersburg), хоть там и Nominatim используется, но запросы эти он не считывал. Может попытаетесь повторить, вдруг получится, но мне кажется там с библиотекой какие-то проблемы.

**Comment by nermakovaa** [comment]
На данный момент самый оптимальный способ - использовать эти библиотеки https://github.com/nikita03565/city-road-network https://github.com/nikita03565/crn-examples и с помощью запуска ноутбука в колабе получить слои. Из преимуществ - быстрая обработка (другим способом такого не добиться). Из недостатков - данные с множеством лишних узлов и прямых (поскольку через osm подгружаются). Обновила ноутбук с примерами получения слоев https://github.com/webebers/city-view/blob/master/notebook/notebook.ipynb. Думаю искомый граф должен состоять из узлов nodelist (перекрестки), poi (центры зданий), дуг path (кратчайшие линии) и edgelist (дороги). Нам может подойти столбцы с геометрией из nodelist, poi, edgelist; название здания из poi, название типа дороги и улицы из edgelist; и необходимо вытащить геометрию из path + название здания из которого линия проводилась.

**Comment by nermakovaa** [comment]
@sevryukov Сергей Юрьевич, доброго времени суток, есть проблемы с получением географии кратчайших расстояний, сделать это через встроенные в osmnx функции не удается, на данный момент слои, необходимые для графа, - удается лишь таким образом получить https://github.com/webebers/city-view/issues/48#issuecomment-1860004354. Правильно ли я понимаю, что для построения графа, необходимо получить всю географию (если Александр Юрьевич хотел получить граф с узлами - центрами зданий и дугами - дорогами/линиями, соединяющими центры зданий с ближайшей дорогой, + узлы это в том числе перекрестки и дуги - это все дороги)? Может Вы сможете подсказать в каком направлении двигаться, чтобы географию получить (дуг - кратчайших расстояний, соединяющих здания и дороги) и если у нас получится решить эту задачу, сможем ли мы построить граф, если к примеру географию всех объектов (узлов и дуг) объединим.

**Comment by sevryukov** [comment]
> географии кратчайших расстояний
Что это такое - давайте определимся что Вы под этим понимаете?

> сделать это через встроенные в osmnx функции не удается
Вижу в комментариях, что были какие-то попытки, но Issue не связан с коммитами и какой код соответствует каким попыткам мне не понять.
Какую задачу, с помощью какого кода пробуете и какая ошибка возникает?


Есть такое понятие, как дорожная сеть. Она м.б. получена и представлена с помощью OSMnx. Дорожная сеть сохраняется в виде графа и, соответственно, граф можно обработать для получения каких-либо метрик или дополнительных данных (например, расстояний между узлами).
Однако сеть дорог не включает в себя здания и предстоит решить задачу соотнесения зданий с узлами графа. Это уже пространственная составляющая (например, поиск ближайшего узла дорожной сети для каждого из зданий с использованием их координат).
Возможно будет полезна вот эта скромная статья, которая показывает как совмещать работу графовой и пространственной составляющей: https://www.codeproject.com/Articles/5328791/Using-OSMnx-for-Graph-Analysis-of-Street-Networks

**Comment by nermakovaa** [comment]
Под географией кратчайших расстояний понимаю дугу, которая соединяет здание (точку - координаты центра здания) с ближайшей дорогой - ребром (перпендикуляр к ближайшему ребру). Полученные результаты хранятся как ребро с координатами начала и конца (два узла определяющие ребро), где начало это координаты здания, а конец - пересечение прямой (перпендикуляра) и ближайшей дороги - но я могу ошибаться, пока так это вижу.  
В osmnx находила встроенную функцию get_nearest_edges, и с помощью этой функции пыталась то что выше упомянула сделать (найти два узла определяющие ребро - кратчайшее расстояние). 
Попробую соотнести центры зданий - узлы с ближайшими узлами графа, состоящего из дорог и перекрестков. Со статьей ознакомлюсь. Спасибо за советы! 
@sevryukov

**Comment by sevryukov** [comment]
@nermakovaa @GeorgiySurkov  как дела, что-нибудь удалось прояснить?

**Comment by nermakovaa** [comment]
Для решения проблемы создали новую задачу https://github.com/webebers/city-view/issues/51, пока над ней работаем, подключили @WenFutao  
@sevryukov

**Comment by nermakovaa** [comment]
Добавила пример построения графа и полученные файлы https://github.com/webebers/city-view/blob/master/notebook/graph.ipynb
Столкнулась с проблемой обработки отрезков - к примеру, если у нас несколько точек пересечения перпендикуляров к одной дуге, - в таком случае мы не можем условно разбить существующую дугу на 2 отрезка и записать их. Необходимо разбить дугу на большее количество отрезков, при этом их требуется запоминать, чтобы start_node и end_node обрабатывать, пока это проблема
Может быть у вас получится разбить дугу, чтобы новые отрезки записать (при этом необходимо записывать имеющиеся дуги, к которым отрезки не были проведены - чтобы граф не потерять). Файл с точками пересечения перпендикуляров - path_node_upd.csv, исходный файл с дугами который нужно разбить edgelist_upd.csv, файл с кратчайшими расстояниями path_upd.csv
@GeorgiySurkov @AnatolyShev @WenFutao

**Comment by nermakovaa** [comment]
https://github.com/webebers/city-view/blob/master/notebook/all_graph.ipynb добавила альтернативный способ создания графа из ближайших перекрестков и зданий - узлы, дороги и кратчайшие расстояния - дуги
