### ISSUE TITLE
Преобразовать данные в пространственный граф

### ISSUE THREAD

**Issue by nermakovaa** [webebers/city-view#51]
У нас есть данные с геометрией, полученные из osmnx. 

Среди данных:
- [edgelist_upd.csv](https://github.com/webebers/city-view/blob/master/data/spb/edgelist_upd.csv) - данные с дорогами
- [nodelist_upd.csv](https://github.com/webebers/city-view/blob/master/data/spb/nodelist_upd.csv) - данные с перекрестками
- [path_upd.csv](https://github.com/webebers/city-view/blob/master/data/spb/path_upd.csv) - данные с кратчайшими расстояниями от здания до дороги (перпендикуляры)
- [poi_upd.csv](https://github.com/webebers/city-view/blob/master/data/spb/poi_upd.csv) - данные с центрами зданий

Необходимо, используя библиотеку NetworkX преобразовать данные в пространственный граф с узлами и дугами. Узлы - это nodelist_upd и poi_upd.csv + необходимо добавить еще один файл с узлами - точками пересечения кратчайших линий с дорогами - их можно получить из поля с геометрией в path_upd. Дуги графа - это path_upd и edgelist_upd.

В результате, искомый граф должен состоять из дуг и узлов, где узлы - центры зданий, перекрестки и точки - в которых кратчайшие расстояния пересекаются с улицами. Дуги - все дороги и кратчайшие расстояния. 

Требуется восстановить граф из имеющихся файлов, используя библиотеку NetworkX (https://www.codeproject.com/Articles/5328791/Using-OSMnx-for-Graph-Analysis-of-Street-Networks) - можно посмотреть как в этой библиотеке данные хранятся и из такого же формата граф получить - в наших данных кажется все для этого есть.

**Comment by GeorgiySurkov** [comment]
Отмечу, что библиотека называется NetworkX, а не Networks.

**Comment by WenFutao** [comment]
Я заново загрузил измененный код в branch, если вам удобно, проверьте, пожалуйста, соответствует ли он требованиям.
![image](https://github.com/webebers/city-view/assets/116686692/a3698f48-95a7-4031-9448-e413d93923fc)

**Comment by WenFutao** [comment]
Я заново загрузил измененный код в branch, если вам удобно, проверьте, пожалуйста, соответствует ли он требованиям.
