### ISSUE TITLE
Дозаполнить паспорт проекта

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view#6]
Необходимо дозаполнить оставшуюся часть паспорта нашего проекта:
https://docs.google.com/document/d/1tjMJwnj4KWGNcaXk_jiwnycUrioC6m1Vas2zzcRJRLo/edit?usp=sharing

**Comment by AnatolyShev** [comment]
Для дозаполнения паспорта проекта понадобится доработать бизнес модель:
https://docs.google.com/document/d/1QNxtH54_BDdaDZRjqYEc9rAJpIDgKnfnfIiiqZkdZeQ/edit?usp=sharing

**Comment by AnatolyShev** [comment]
@dipmoaiaismo Так как до п.19 в паспорте нет мест, где не требовалось бы хорошо разбираться в технической части, есть идея направить тебя на написание п.25-29. Там нужно лучше расписать характеристику проблемы клиентов.

**Comment by dipmoaiaismo** [comment]
> @dipmoaiaismo Так как до п.19 в паспорте нет мест, где не требовалось бы хорошо разбираться в технической части, направляю тебя на написание п.25-29. Там нужно лучше расписать характеристику проблемы клиентов.

хорошо

**Comment by dipmoaiaismo** [comment]
Я заполнил с 25 по 28 пункты, чтобы заполнить пункт 29 у меня недостаточно знаний. Как будет время проверьте пожалуйста.
[Паспорт проекта 2.docx](https://github.com/webebers/city-view-back/files/13443501/2.docx)

**Comment by AnatolyShev** [comment]
@dipmoaiaismo Я проверил и подправил некоторые фразы. В принципе, всё хорошо расписано, и изменения я уже внёс.

**Comment by AnatolyShev** [comment]
При 29 пункта нужно исследовать рынок и рентабельность нашего бизнеса. Вот полезные ссылки и материалы от нашего бизнес трекера:
1) https://zakupki.gov.ru/epz/order/extendedsearch/results.html?morphology=on&search-filter=Дате+размещения&pageNumber=1&sortDirection=false&recordsPerPage=_10&showLotsInfoHidden=false&sortBy=UPDATE_DATE&fz44=on&currencyIdGeneral=-1&publishDateFrom=01.11.2022&ktruCodeNameList=71.11.30.000-00000001%26%26%26Услуги+по+территориальному+планированию+и+планировке+территории

2) https://zakupki.gov.ru/epz/order/extendedsearch/results.html?searchString=улично-дорожная+сеть&morphology=on&search-filter=+Цене&pageNumber=1&sortDirection=false&recordsPerPage=_10&showLotsInfoHidden=false&sortBy=PRICE&fz44=on&fz223=on&af=on&ca=on&pc=on&pa=on&currencyIdGeneral=-1&publishDateFrom=01.11.2022

3) [4 гр финмодель арт (2).xlsx](https://github.com/webebers/city-view/files/13477903/4.2.xlsx)

**Comment by AnatolyShev** [comment]
Помимо этого весь паспорт нужно будет перенести на портал с нашим проектом: 
https://pt.2035.university/project/servis-po-analizu-gorodskoj-topologii/form
